env:
        - REBAR_DEPS_DIR=$TRAVIS_BUILD_DIR/deps
sudo: false
language: elixir
elixir:
        - 1.2.3
otp_release:
        - 18.2
before_install:
        - . $HOME/.nvm/nvm.sh
        - nvm install stable
        - nvm use stable
        - npm --version
        - export CHROME_BIN=chromium-browser
        - export DISPLAY=:99.0
before_script:
        - sh -e /etc/init.d/xvfb start
        - sleep 1  # give server time to start
after_script:
        - cat /home/travis/build/xadhoom/detectino-core/apps/dt_web/webapp/npm-debug.log
script:
        - "pushd apps/dt_web/webapp; npm install; npm run test; popd"
        - "mix deps.get && mix deps.compile && mix coveralls.travis --umbrella"
