env:
        - REBAR_DEPS_DIR=$TRAVIS_BUILD_DIR/deps
sudo: false
language: elixir
elixir:
        - 1.2.3
otp_release:
         - 18.2
script:
        - "mix deps.get && mix deps.compile && mix coveralls.travis --umbrella"
